### ISSUE TITLE
Фон с текстуркой

### ISSUE THREAD

**Issue by momo-hash1** [momo-hash1/restaurant_valentino#1]
Я не понимаю как лучше сделать этот фон
![image](https://github.com/momo-hash1/restaurant_valentino/assets/115136524/8bb9a56f-6060-4eba-bfd9-755c292ceb79)

**Comment by foxhable** [comment]
Что значит "лучше"?

**Comment by foxhable** [comment]
Я сделал оптимизированный фон, который повторяется по вертикали, используй его с включенным `background-repeat: repeat;`, так же сделай цвет заднего фона у документа `#30312F`. Дополнительная хренm, типа текста и линий добавляй отдельно к секциям любыми удобными способами

[Скачать фон](https://drive.google.com/file/d/1hbjTp5gbnm2mc5xjjIaH7JtF_FkQZsj7/view?usp=sharing)
